- name: String Replace
  uses: bejoistic/str-replace@v1.0.2
  with:
    # A regular expression of files to include in our find and replace
    include: # optional, default is .*
    # A regular expression of files to exclude in our find and replace
    exclude: # optional, default is .git
    # The string we want to replace
    find: 
    # The new string to replace with
    replace: 
